theme: jekyll-theme-minimal
title: Heya! 
description: I'm a Data Enthusiast, currently working in my first career job after graduating from my postgraduate studies. My name is Isabell (she/her), but most people call me Isi [ˈɪziː]!
