theme: jekyll-theme-minimal
title: Heya! 
description: I'm a student at Master's level, currently looking for a job in the greater Aberdeen area. My name is Isabell (she/her), but most people call me Isi [ˈɪziː]!
